core/models/record.py
import uuid

from datetime import datetime

from sqlalchemy.dialects.postgresql import UUID

from core import db


class Record(db.Model):
    __tablename__ = 'records'

    id = db.Column(UUID(), primary_key=True, nullable=False)
    description = db.Column(db.String(140))
    pub_date = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(UUID(), db.ForeignKey('users.id'))

    def __init__(self, *args, **kwargs):
        self.id = uuid.uuid4().urn
        super().__init__(*args, **kwargs)

    def __repr__(self):
        return f'<id {self.id}>'

    def __str__(self):
        return f'<Record {self.description}>'

core/forms/records.py
from wtforms import Form, TextAreaField, validators

from core import db
from core.models import User


class RecordCreateForm(Form):
    description = TextAreaField('Description', [
        validators.DataRequired(),
        validators.Length(min=1, max=140),
    ])

core/views/records.py
from flask import (Blueprint, flash, g, redirect, render_template, request,
                   url_for)
from werkzeug.exceptions import abort

from core import db
from core.config import Config
from core.forms import RecordCreateForm
from core.models import Record
from core.views.auth import login_required

bp = Blueprint('records', __name__, url_prefix='/records')


@bp.route('/')
def index():
    """Show all the records, order by publication date."""
    page = request.args.get('page', 1, type=int)
    records = Record.query.order_by(Record.pub_date.desc()).paginate(
        page, Config.POSTS_PER_PAGE, True
    )
    next_url = url_for('records.index', page=records.next_num) \
        if records.has_next else None
    prev_url = url_for('records.index', page=records.prev_num) \
        if records.has_prev else None

    return render_template(
        'records/index.html',
        records=records.items,
        next_url=next_url,
        prev_url=prev_url,
    )


def get_record(record_id, check_author=True):
    """Get a record by id dnd check record owner"""
    record = Record.query.get(record_id)

    if record is None:
        abort(404, f"Record id {record_id} doesn't exist.")

    if check_author and record.user_id != g.user.id:
        abort(403)

    return record


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    """Create a new record for the current user."""
    form = RecordCreateForm(request.form)
    if request.method == 'POST' and form.validate():
        record = Record(description=form.description.data, user_id=g.user.id)
        db.session.add(record)
        db.session.commit()
        flash('Record create!')
        return redirect(url_for('records.index'))

    return render_template('records/create.html', form=form)


@bp.route('/<record_id>/update', methods=('GET', 'POST'))
@login_required
def update(record_id):
    """Update a new record for the current user."""
    record = get_record(record_id)
    form = RecordCreateForm(request.form, record)
    if request.method == 'POST' and form.validate():
        record.description = form.description.data
        record.user_id = g.user.id
        db.session.add(record)
        db.session.commit()
        flash('Record create!')
        return redirect(url_for('records.index'))

    return render_template('records/update.html', form=form, record_id=record_id)


@bp.route('/<record_id>/delete', methods=('POST',))
@login_required
def delete(record_id):
    """Delete a record."""
    record = get_record(record_id)
    db.session.delete(record)
    db.session.commit()
    return redirect(url_for('records.index'))

core/templates/records/create.html
{% extends "base.html" %}

{% block title %}Create record{% endblock %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="form-group">
            <form method=post>
                {{ form.csrf_token }}
                <h1><label for="description">New record</label></h1>
                <ul>
                    {% for error in form.description.errors %}
                        <li class="text-red">
                            {{ error }}
                        </li>
                    {% endfor %}
                </ul>
                <textarea class="form-control" name="description" id="description" cols="100" rows="10">{{form.description.data}}</textarea>
                <button type=submit class="btn btn-primary">Save</button>
            </form>
      </div>
    </div>
{% endblock %}

core/templates/records/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block content %}
  <div class="container page">
    {% for record in records %}
      <div class="container">
        {% if g.user == record.user %}
          <p><a href="{{ url_for('records.update', record_id=record.id)}}"><b>ID:</b> {{ record.id }}</a></p>
        {% else %}
          <p><b>ID:</b> {{ record.id }}</p>
        {% endif %}
        <p><b>Description:</b> {{ record.description }}</p>
        <p><b>Author:</b> {{ record.user.first_name }} {{ record.user.last_name }}</p>
        <p><b>Publication date:</b> {{ moment(record.pub_date).format('LLL') }}</p>
        <hr>
      </div>
    {% else %}
      <div class="container">
        <h1>Not records.</h1>
      </div>
    {% endfor %}
    <div class="container">
      {% if prev_url %}
        <div class="pull-left">
          <a href="{{ prev_url }}">Newer records</a>
        </div>
      {% endif %}
      {% if next_url %}
      <div class="pull-right">
        <a href="{{ next_url }}">Older records</a>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

core/templates/records/update.html
{% extends "base.html" %}

{% block title %}Update record{% endblock %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="form-group">
            <form method=post>
                {{ form.csrf_token }}
                <h1><label for="description">Update record</label></h1>
                <ul>
                    {% for error in form.description.errors %}
                        <li class="text-red">
                            {{ error }}
                        </li>
                    {% endfor %}
                </ul>
                <textarea class="form-control" name="description" id="description" cols="100" rows="10">{{form.description.data}}</textarea>
                <button type=submit class="btn btn-primary">Update</button>
            </form>
            <form action="{{ url_for('records.delete', record_id=record_id) }}" method="post">
                <input class="btn btn-danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
            </form>
        </div>
    </div>
{% endblock %}