core/views/auth.py
import functools

from flask import (Blueprint, flash, g, redirect, render_template, request,
                   session, url_for)

from core import db
from core.forms import LoginForm, RegistrationForm
from core.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


def redirect_if_logged(view):
    """If a user id is stored in the session,
    redirect user from login and registration page."""
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user:
            return redirect(url_for('records.index'))

        return view(**kwargs)

    return wrapped_view


def login_required(view):
    """View decorator that redirects anonymous users to the login page."""
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view


@bp.before_app_request
def load_logged_in_user():
    """If a user id is stored in the session, load the user object from
    the database into ``g.user``."""
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id).first()


@bp.route('/register', methods=('GET', 'POST'))
@redirect_if_logged
def register():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)


@bp.route('/login', methods=('GET', 'POST'))
@redirect_if_logged
def login():
    form = LoginForm(request.form)
    error = None
    if request.method == 'POST' and form.validate():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('records.index'))
        else:
            error = 'Incorrect email or password.'
    return render_template('auth/login.html', form=form, error=error)


@bp.route('/logout')
def logout():
    """Clear the current session, including the stored user id."""
    session.clear()
    return redirect(url_for('records.index'))

core/views/records.py
from flask import (Blueprint, flash, g, redirect, render_template, request,
                   url_for)
from werkzeug.exceptions import abort

from core import db
from core.config import Config
from core.forms import RecordCreateForm
from core.models import Record
from core.views.auth import login_required

bp = Blueprint('records', __name__, url_prefix='/records')


@bp.route('/')
def index():
    """Show all the records, order by publication date."""
    page = request.args.get('page', 1, type=int)
    records = Record.query.order_by(Record.pub_date.desc()).paginate(
        page, Config.POSTS_PER_PAGE, True
    )
    next_url = url_for('records.index', page=records.next_num) \
        if records.has_next else None
    prev_url = url_for('records.index', page=records.prev_num) \
        if records.has_prev else None

    return render_template(
        'records/index.html',
        records=records.items,
        next_url=next_url,
        prev_url=prev_url,
    )


def get_record(record_id, check_author=True):
    """Get a record by id dnd check record owner"""
    record = Record.query.get(record_id)

    if record is None:
        abort(404, f"Record id {record_id} doesn't exist.")

    if check_author and record.user_id != g.user.id:
        abort(403)

    return record


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    """Create a new record for the current user."""
    form = RecordCreateForm(request.form)
    if request.method == 'POST' and form.validate():
        record = Record(description=form.description.data, user_id=g.user.id)
        db.session.add(record)
        db.session.commit()
        flash('Record create!')
        return redirect(url_for('records.index'))

    return render_template('records/create.html', form=form)


@bp.route('/<record_id>/update', methods=('GET', 'POST'))
@login_required
def update(record_id):
    """Update a new record for the current user."""
    record = get_record(record_id)
    form = RecordCreateForm(request.form, record)
    if request.method == 'POST' and form.validate():
        record.description = form.description.data
        record.user_id = g.user.id
        db.session.add(record)
        db.session.commit()
        flash('Record create!')
        return redirect(url_for('records.index'))

    return render_template('records/update.html', form=form, record_id=record_id)


@bp.route('/<record_id>/delete', methods=('POST',))
@login_required
def delete(record_id):
    """Delete a record."""
    record = get_record(record_id)
    db.session.delete(record)
    db.session.commit()
    return redirect(url_for('records.index'))

core/templates/base.html
<!DOCTYPE html>
<html class="bg-black">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- bootstrap 3.0.2 -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- font Awesome -->
    <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ url_for('static', filename='css/AdminLTE.css') }}" rel="stylesheet" type="text/css" />
    <!-- Main style -->
    <link href="{{ url_for('static', filename='css/main.css') }}?v=1135" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="bg-black">

    {% block navbar %}{% endblock %}

    {% block content %}{% endblock %}

    <!-- jQuery 2.0.2 -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" type="text/javascript"></script>
    {{ moment.include_moment() }}

  </body>
</html>

core/templates/navbar.html
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('index') }}">Home</a></li>
        <li><a href="{{ url_for('records.create') }}">Create record</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if g.user %}
          <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
        {% else %}
          <li><a href="{{ url_for('auth.register') }}">Register</a>
          <li><a href="{{ url_for('auth.login') }}">Log In</a>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>